from . import approval_integration_module
from . import approval_level
from . import approval_notification_event
from . import approval_delegation
from . import approval_document_type
from . import approval_rule
from . import approval_rule_line
from . import approval_user_right
from . import approval_request
from . import approval_request_line
from . import approval_history
from . import approval_mixin
from . import approval_setup_config
from . import res_users_approval
from . import sale_order_approval
from . import purchase_order_approval
from . import account_move_approval
from . import account_payment_approval
from . import stock_picking_approval
from . import stock_scrap_approval
from . import mrp_production_approval
from . import mrp_unbuild_approval